name: dart_csv
description: A Dart package to write comma separated values to a file.
version: 1.0.0
repository: https://github.com/JonasPrimbs/dart_csv

environment:
  sdk: ^3.2.0

dependencies:
  intl: ^0.19.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
